version: "2"
services:
    base:
        build: .
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        restart: always
        environment:
            MYSQL_USER: vicomtech
            MYSQL_PASSWORD: vicomtech
            MYSQL_ROOT_PASSWORD: password
        networks:
            - default
volumes:
    persistent:
