FROM ubuntu:14.04

RUN apt-get -y update

# dependencies
RUN apt-get -y install vim\
 nginx\
 python-dev\
 python-flup\
 python-pip\
 python-ldap\
 expect\
 git\
 wget\
 netcat\
 net-tools\
 memcached\
 sqlite3\
 libcairo2\
 libcairo2-dev\
 python-cairo\
 python-rrdtool\
 pkg-config\
 nodejs

# python dependencies
RUN pip install django==1.5.12\
 python-memcached==1.53\
 django-tagging==0.3.1\
 twisted==11.1.0\
 txAMQP==0.6.2

RUN apt-get update
RUN apt-get install -y autoconf autotools-dev net-tools build-essential libssl-dev bsdmainutils git libboost-all-dev libtool pkg-config python-cffi
RUN apt-get install -y sudo
RUN useradd -m statoshi && echo "statoshi:statoshi" | chpasswd && adduser statoshi sudo


RUN mkdir /home/statoshi/.bitcoin && mkdir /home/statoshi/.scripts && mkdir /home/statoshi/log
RUN cd /home/statoshi/.scripts && wget "http://yabtcn.info/statoshi/bitcoind.check.example" -O bitcoind.check.sh >/dev/null 2>&1 && wget "http://yabtcn.info/statoshi/statsd.check.example" -O statsd.check.sh >/dev/null 2>&1 && wget "http://yabtcn.info/statoshi/systemmetricsd.check.example" -O systemmetricsd.check.sh >/dev/null 2>&1 && chmod +x *.sh


RUN cd /opt/ && git clone https://github.com/ArtDodger/statoshi
ADD configure.ac /opt/statoshi/
RUN cd /opt/statoshi && ./autogen.sh
RUN cd /opt/statoshi && ./configure --disable-wallet --with-cli --without-gui --enable-hardening --without-miniupnpc
RUN cd /opt/statoshi && make
RUN cd /opt/statoshi && make install

# install graphite
RUN git clone -b 0.9.15 --depth 1 https://github.com/graphite-project/graphite-web.git /usr/local/src/graphite-web
WORKDIR /usr/local/src/graphite-web
RUN python ./setup.py install

# install whisper
RUN git clone -b 0.9.15 --depth 1 https://github.com/graphite-project/whisper.git /usr/local/src/whisper
WORKDIR /usr/local/src/whisper
RUN python ./setup.py install

# install carbon
RUN git clone -b 0.9.15 --depth 1 https://github.com/graphite-project/carbon.git /usr/local/src/carbon
WORKDIR /usr/local/src/carbon
RUN python ./setup.py install

# install statsd
RUN git clone -b v0.8.0 https://github.com/etsy/statsd.git /opt/statsd

# config graphite
ADD conf/opt/graphite/conf/*.conf /opt/graphite/conf/
ADD conf/opt/graphite/webapp/graphite/local_settings.py /opt/graphite/webapp/graphite/local_settings.py
ADD conf/opt/graphite/webapp/graphite/app_settings.py /opt/graphite/webapp/graphite/app_settings.py
RUN python /opt/graphite/webapp/graphite/manage.py collectstatic --noinput

# config statsd
ADD conf/opt/statsd/config_*.js /opt/statsd/

# config nginx
RUN rm /etc/nginx/sites-enabled/default
ADD conf/etc/nginx/nginx.conf /etc/nginx/nginx.conf
ADD conf/etc/nginx/sites-enabled/graphite-statsd.conf /etc/nginx/sites-enabled/graphite-statsd.conf

# init django admin
ADD conf/usr/local/bin/django_admin_init.exp /usr/local/bin/django_admin_init.exp
RUN /usr/local/bin/django_admin_init.exp

# logging support
RUN mkdir -p /var/log/carbon /var/log/graphite /var/log/nginx
ADD conf/etc/logrotate.d/graphite-statsd /etc/logrotate.d/graphite-statsd

# daemons
ADD conf/etc/service/carbon/run /etc/service/carbon/run
ADD conf/etc/service/carbon-aggregator/run /etc/service/carbon-aggregator/run
ADD conf/etc/service/graphite/run /etc/service/graphite/run
ADD conf/etc/service/statsd/run /etc/service/statsd/run
ADD conf/etc/service/nginx/run /etc/service/nginx/run

# default conf setup
ADD conf /etc/graphite-statsd/conf
ADD conf/etc/my_init.d/01_conf_init.sh /etc/my_init.d/01_conf_init.sh

# cleanup
RUN apt-get clean\
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get update && apt-get -y install apt-transport-https 
RUN echo "deb https://packagecloud.io/grafana/stable/debian/ wheezy main" >> /etc/apt/sources.list
RUN wget -qO - "https://packagecloud.io/gpg.key" | apt-key add - >/dev/null 2>&1
RUN apt-get update
RUN apt-get install -y grafana

RUN wget "http://yabtcn.info/statoshi/bitcoind.conf.example" -O /etc/default/bitcoind >/dev/null 2>&1 && wget "http://yabtcn.info/statoshi/bitcoind.init.example" -O /etc/init.d/bitcoind >/dev/null 2>&1
RUN chmod +x /etc/init.d/bitcoind
RUN apt-get install -y rcconf sysv-rc-conf cron
RUN update-rc.d bitcoind defaults && update-rc.d grafana-server defaults && update-rc.d cron defaults
RUN rm /etc/crontab && wget "http://yabtcn.info/statoshi/crontab.example" -O /etc/crontab >/dev/null 2>&1

ADD my_script.sh /etc/init.d/
RUN chmod 775 /etc/init.d/my_script.sh

RUN cd /root/ && git clone http://github.com/jlopp/bitcoin-utils
ADD bitcoin.conf /root/.bitcoin/

WORKDIR /root

ADD ./provisioning /etc/grafana/provisioning
ADD ./config.ini /etc/grafana/config.ini
ADD ./dashboards /var/lib/grafana/dashboards

# defaults
EXPOSE 82 3000 2003-2004 2023-2024 8125 8125/udp 8126 18332

