# Copy this file with your own configuration and save it as conf.py

DOCK_NETWORK_NAME_ZCH = 'zcashnet'
DOCK_NETWORK_SUBNET_ZCH ='172.191.0.0/16'
DOCK_NETWORK_GW_ZCH = '172.191.254.254'

DOCK_CONTAINER_NAME_PREFIX_ZCH = 'zch'
DOCK_IMAGE_NAME_ZCH = 'zch'

DOCK_IMAGE_NAME_DASHBOARD = 'grph_dashboard'
DOCK_IMAGE_NAME_CLIENT_ZCH= 'zch_client'
DOCK_IMAGE_NAME_DATAFEED = 'grph_datafeed'
DOCK_IMAGE_NAME_API_ZCH = 'zch_api'

DOCK_MACHINE_NAME_BLOCKSCI_ZCH = 'ZCH_blocksci'
DOCK_IMAGE_NAME_BLOCKSCI= 'blocksci'

DOCK_MACHINE_NAME_DASHBOARD_ZCH = 'zch_dashboard'
DOCK_MACHINE_NAME_DATAFEED_ZCH = 'zch_datafeed'


ZCH_RPC_PORT = 18333
ZCH_RPC_USER = 'uab'
ZCH_RPC_PASSWD = 'uabpassword'

